### PR TITLE
Fix for #17

### LINKED ISSUE #17: Resource fails with `open /root/.ssh/config: no such file or directory`
So I can't be 100% sure, but after a upgrade the other day, all our resources started failing with:

```
open /root/.ssh/config: no such file or directory
```
Looking at the change I would guess this change is the offender:

https://github.com/concourse/hg-resource/commit/75d02708b4bcbbccb88577efea1c81a59d1c32db#diff-539560c8bb7f0b5eb133bea29c18badb2943d366769fff45fb33a54120bde909R54

Looking at the previous `atomicSave` function it looks like it actually checks for the dir and creates it if it doesn't exists.

Are we doing anything wrong since we're using root, should we run as another user, should we have the go module create the dir if necessary or should we have the directory created in the docker file instead?

### PR DESCRIPTION
**Pull request by s2hc-johan**
Fixed ubuntu docker file and ssh dir issue

Created a function, based on the old atomicSave, that creates the `.ssh`
dir.

This should close #17, I'm not that fluent in golang, and I don't really know how I would setup ssh to be able to test. But we built an image and our pipeline works with it.

### CODE REVIEW

**Comment by xtremerui** [comment]
Thx for submitting the PR. Would you be able to add a test for the `mkSSHDir` function? You could follow the example of `startSshAgent ` https://github.com/concourse/hg-resource/blob/f50064ed4a8eca504233dab7712f4455105dd291/hgresource/ssh_test.go#L36

to invoke the function and assert on the result whether the dir is created correctly. So it'd be sth like
```
Context : when making ssh dir {
    It should create the dir {
         mkSSHDir(some-dir)
        
       Expect some-dir is created
    }
}
```
you dont need to start up ssh agent for this unit test.

File: hgresource/ssh_test.go [hunk 1]
```diff
@@ -50,4 +51,42 @@ var _ = Describe("Ssh", func() {
 			}).Should(BeFalse())
 		})
 	})
+
+	homeDir := "/tmp"
+	sshDir := path.Join(homeDir, ".ssh")
+	sshClientConfigFile := path.Join(homeDir, ".ssh/config")
```
Comment (xtremerui) [inline hgresource/ssh_test.go]:
```suggestion
```

these could be moved inside the context.

File: hgresource/ssh_test.go [hunk 2]
```diff
@@ -50,4 +51,42 @@ var _ = Describe("Ssh", func() {
...
+
+	Context("When configuring ssh", func() {
+		It("can crete the directory", func() {
```
Comment (xtremerui) [inline hgresource/ssh_test.go:60]:
```suggestion
	homeDir := "/tmp"
	sshDir := path.Join(homeDir, ".ssh")
	sshClientConfigFile := path.Join(homeDir, ".ssh/config")
	
		It("can crete the directory", func() {
```

File: hgresource/ssh_test.go [hunk 3]
```diff
@@ -50,4 +51,42 @@ var _ = Describe("Ssh", func() {
 			}).Should(BeFalse())
 		})
 	})
+
+	homeDir := "/tmp"
+	sshDir := path.Join(homeDir, ".ssh")
+	sshClientConfigFile := path.Join(homeDir, ".ssh/config")
+
+	Context("When configuring ssh", func() {
```
Comment (xtremerui) [inline hgresource/ssh_test.go:55]:
```suggestion
	Context("When configuring ssh", func() {
		homeDir := "/tmp"
	        sshDir := path.Join(homeDir, ".ssh")
	        sshClientConfigFile := path.Join(homeDir, ".ssh/config")
```

File: hgresource/ssh_test.go [hunk 4]
```diff
@@ -50,4 +51,42 @@ var _ = Describe("Ssh", func() {
...
+			err := mkSSHDir(sshClientConfigFile)
+			Expect(err).To(BeNil())
+
+			// check that the directory now exists
+			_, resultErr := os.Stat(sshDir)
+			Expect(resultErr).To(BeNil())
+
+			// cleanup
+			err = os.RemoveAll(sshDir)
+			Expect(err).To(BeNil())
```
Comment (xtremerui) [inline hgresource/ssh_test.go]:
```suggestion
```

File: hgresource/ssh_test.go [hunk 5]
```diff
@@ -50,4 +51,42 @@ var _ = Describe("Ssh", func() {
...
+			// make sure the directory already exists
+			sshDirErr := os.MkdirAll(sshDir, 0700)
+			Expect(sshDirErr).To(BeNil())
+
+			err := mkSSHDir(sshClientConfigFile)
+			Expect(err).To(BeNil())
+
+			// cleanup
+			err = os.RemoveAll(sshDir)
+			Expect(err).To(BeNil())
```
Comment (xtremerui) [inline hgresource/ssh_test.go]:
```suggestion
```
this could be move the an afereach within the context so it will run after each `It()`.

File: hgresource/ssh_test.go [hunk 6]
```diff
@@ -50,4 +51,42 @@ var _ = Describe("Ssh", func() {
...
+		})
+
```
Comment (xtremerui) [inline hgresource/ssh_test.go:87]:
```suggestion
AfterEach(func()  {
                        // cleanup
			err = os.RemoveAll(sshDir)
			Expect(err).To(BeNil())
})
```

**Review by xtremerui — CHANGES_REQUESTED** [review]
thx for the test. Just some refactors then we are good to go.

**Comment by s2hc-johan** [comment]
I'll update with a new commit. `AfterEach` be before or after the `It` functions?

**Comment by s2hc-johan** [comment]
seemed to work with before.

**Comment by s2hc-johan** [comment]
I can't really follow why the CI failed. The docker commands builds for me locally

**Comment by xtremerui** [comment]
we are reorganizing the github team configure and thus affects the CI. I will rerun it when CI is stable.
